# Generated by Django 2.2 on 2019-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('contract_type', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis de Trabalho')], max_length=50)),
                ('status', models.CharField(choices=[('Y', 'Sim'), ('N', 'Não')], default='Y', max_length=1)),
            ],
        ),
    ]
