# Generated by Django 2.2 on 2019-04-12 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('location_city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('initial_salary', models.FloatField()),
                ('final_salary', models.FloatField()),
                ('contract_type', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis de Trabalho')], max_length=50)),
                ('status', models.CharField(choices=[('N', 'Não Iniciada'), ('A', 'Em Andamento'), ('C', 'Concluida')], default='A', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeel.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('job_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_job', to='skeel.JobVacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('job_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_job', to='skeel.JobVacancy')),
            ],
        ),
    ]
