# Generated by Django 2.2 on 2019-04-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='status',
            field=models.CharField(choices=[('N', 'Não Iniciada'), ('A', 'Em Andamento'), ('C', 'Concluida')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefits_vacancy', to='skeel.JobVacancy')),
            ],
        ),
    ]
