# Generated by Django 2.2 on 2019-04-10 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skeel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvacancy',
            old_name='salary',
            new_name='final_salary',
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='initial_salary',
            field=models.FloatField(default=500.9),
            preserve_default=False,
        ),
    ]
