# Generated by Django 2.2 on 2019-04-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeel', '0004_auto_20190412_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requisito',
            new_name='JobBenefit',
        ),
        migrations.RenameField(
            model_name='jobbenefit',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobbenefit',
            old_name='vaga',
            new_name='vacancy',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
