# Generated by Django 2.2 on 2019-04-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeel', '0007_auto_20190412_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('job_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_job', to='skeel.JobVacancy')),
            ],
        ),
        migrations.DeleteModel(
            name='JobCongratulations',
        ),
    ]
